### ISSUE TITLE
https://index.docker.io/v2 requests authentication

### ISSUE THREAD

**Issue by TheAbsoluteTruth** [ryandaniels/docker-script-find-latest-image-tag#4]
https://index.docker.io/v2 requests authentication

For example the command:

`./docker_image_find_tag.sh -n portainer -i 5526251cc61f -f 2.13. -l 10 -v`

outputs:
```
Using IMAGE_NAME: portainer
Using REGISTRY: https://index.docker.io/v2
Found Image ID Source: sha256:5526251cc61f126f2c1da1875aae113c9af05a5679123dde2f6c15d12754b103

Error 401 from: https://index.docker.io/v2/library/portainer/tags/list
HTTP_BODY: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"library/portainer","Action":"pull"}]}]}
```

**Comment by ryandaniels** [comment]
This isn't actually an authentication issue, the script is working properly and getting proper authentication.
The problem is the image name you are using needs to be portainer/portainer and not just portainer. 
Updated documentation with PR #5 to help with this until can fix properly (if that's even possible).

**Comment by ryandaniels** [comment]
No other fix possible, upstream issue they did on purpose.
